# action.yaml
name: "BMJ Custom Github Action to retrieve the latest version number from ECR"
description: "BMJ Custom Github Action to retrieve the latest version number from ECR"
inputs:
  ecr_name:
    description: "ECR Name"
    required: true
    default: "name"

outputs:
  ecr_version:
    description: "Version Number"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ecr_name}}
