# action.yaml
name: "BMJ Custom Github Action"
description: "Check ther version number of an ECR and get a new Number based on the result"
inputs:
  ecr_name:
    description: "ECR Name"
    required: true
    default: "name"
  REPOSITORY_NAME:
    description: "Name of ECR repository"
    required: true
outputs:
  ecr_version:
    description: "Version Number"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ecr_name}}
    #- ${{ inputs.REPOSITORY_NAME }}
